# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('similarity', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SimilarUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('similarity', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
        ),
    ]
