# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('event_dim_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=1000)),
                ('attraction_id', models.IntegerField()),
                ('attraction_name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EventRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_user', models.IntegerField()),
                ('serial_event', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_event', models.IntegerField()),
                ('serial_user', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ts', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='SimilarItems',
            new_name='SimilarEvents',
        ),
        migrations.RenameField(
            model_name='similarevents',
            old_name='item1',
            new_name='serial_event1',
        ),
        migrations.RenameField(
            model_name='similarevents',
            old_name='item2',
            new_name='serial_event2',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user1',
            new_name='serial_user1',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user2',
            new_name='serial_user2',
        ),
    ]
