# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20170217_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecommendations',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userrecommendations',
            name='score',
            field=models.FloatField(),
        ),
    ]
