# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20170222_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRecommendations',
        ),
        migrations.DeleteModel(
            name='UserRecommendations',
        ),
    ]
