# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_auto_20170222_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarevents',
            old_name='event1_dim_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='similarevents',
            old_name='event2_dim_id',
            new_name='similar',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user1_dim_id',
            new_name='similar',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user2_dim_id',
            new_name='user',
        ),
    ]
