# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_auto_20170222_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarusers',
            old_name='similar',
            new_name='similarqq',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user',
            new_name='userqq',
        ),
    ]
