# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_auto_20170222_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarusers',
            old_name='similarqq',
            new_name='similar',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='userqq',
            new_name='user',
        ),
    ]
