# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20170222_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarusers',
            old_name='similar',
            new_name='similarqqqq',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user',
            new_name='userqfvv',
        ),
    ]
