# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0010_auto_20170222_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarevents',
            old_name='event',
            new_name='event_dim_id',
        ),
        migrations.RenameField(
            model_name='similarevents',
            old_name='similar',
            new_name='similar_event_dim_id',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='similar',
            new_name='similar_user_id',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user',
            new_name='user_id',
        ),
    ]
