# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_auto_20170223_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_id', models.IntegerField()),
                ('attraction_name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='SimilarEvents',
            new_name='SimilarAttractions',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RenameField(
            model_name='similarattractions',
            old_name='event_dim_id',
            new_name='attraction_id',
        ),
        migrations.RenameField(
            model_name='similarattractions',
            old_name='similar_event_dim_id',
            new_name='similar_attraction_id',
        ),
    ]
