# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_auto_20170223_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarattractions',
            name='attraction_id',
        ),
        migrations.RemoveField(
            model_name='similarusers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='attraction',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='similarattractions',
            name='attraction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recommend.Attraction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarusers',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recommend.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
