# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_auto_20170306_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarattractions',
            old_name='attraction',
            new_name='attraction_id',
        ),
        migrations.RenameField(
            model_name='similarusers',
            old_name='user',
            new_name='user_id',
        ),
    ]
