# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0016_auto_20170310_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='app_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_event_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_name',
            field=models.CharField(max_length=2000),
        ),
    ]
