# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0017_auto_20170310_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='attraction_event_name',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='attraction_start_ts',
        ),
    ]
