# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0018_auto_20170310_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_event_name',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
